from __future__ import annotations

from .agent import (
    AgentState,
    Transcript,
    _message_tokens,
    _pack_messages_with_toons,
    _packed_history_note,
    run_agent,
    run_turn,
)
from .providers import (
    AssistantMessage,
    ChatMessage,
    CompletionClient,
    SystemMessage,
    ToolCall,
    ToolMessage,
    ToolResult,
    ToolSpec,
    UserMessage,
)
from . import agent, cli, providers, runtime, tools
from .providers import (
    APIStatusError,
    ShimSpec,
    command_env,
    detect_available_shims,
    http_client,
    join_model_spec,
    list_models_for_shim,
    load_json,
    normalize_jsonlike,
    resolve_shim,
    run_cmd,
    save_json,
    serialize_json,
    serialize_toon,
    split_model_spec,
    validate_shim,
    which,
)
from .runtime import (
    AUDIT_SYSTEM_PROMPT,
    BASE_SYSTEM_PROMPT,
    BUDGETS,
    CONFIG_PATH,
    DEFAULT_UNATTENDED_TIMEOUT_SECONDS,
    INTERACTIVE_SYSTEM_PROMPT,
    MAX_BASH_CMD_BYTES,
    MAX_CONTEXT_TOKENS,
    NONINTERACTIVE_SYSTEM_PROMPT,
    STDERR,
    STDOUT,
    Path,
    Prompt,
    RuntimeBudgets,
    SessionContext,
    __version__,
    _ASK_SYSTEM_SUFFIX,
    _BASH_IMPORTANT_LINE_RE,
    _FALSY_VALUES,
    _READ_ONLY_TOOLS,
    _TRUTHY_VALUES,
    _cfg_path,
    _debug_log,
    _debug_log_path,
    _debug_logger,
    _derive_runtime_budgets,
    _ensure_private_dir,
    _flag,
    _fmt,
    _format_duration,
    _init_debug_log,
    _load_cfg,
    _model,
    _msg_to_dict,
    _pick_model,
    _print,
    _rel,
    _save_cfg,
    _show_and_clip,
    _shim_name,
    _sys_file,
    _truncate_long_lines,
    _wrap_code_block,
    abort,
    active_system_prompt,
    active_tool_specs,
    ask_system_prompt,
    audit_system_prompt,
    base_system_prompt,
    clip_tokens,
    count_tokens,
    decode_tokens,
    encode_tokens,
    ensure_api_env,
    fail,
    format_tokens,
    get_client,
    get_tokenizer,
    http_client,
    interactive_system_prompt,
    list_all_model_ids,
    load_session_text,
    logging,
    noninteractive_system_prompt,
    note_tool,
    os,
    preview,
    read_only_tool_specs,
    render_model_list,
    require_api_env,
    require_command_env,
    resolve_active_shim,
    resolve_path,
    session_text,
    show,
    time,
    tool_description,
    truncate_str_to_tokens,
)

from .tools import (
    AskArgs,
    BashArgs,
    ListArgs,
    ReadArgs,
    ReplaceArgs,
    SearchArgs,
    SlocArgs,
    TodoArgs,
    TodoItem,
    TOOL_REGISTRY,
    ToolHandler,
    ToolRegistry,
    WebfetchArgs,
    WebfetchOptions,
    _WEBFETCH_ALLOWED_METHODS,
    _bash_payload,
    _format_todos,
    _html_to_markdown,
    _positive_int,
    _render_bash_preview,
    _validate_url_safe,
    _webfetch_payload,
    _webfetch_response_headers,
    _webfetch_response_text,
    _webfetch_structured_text,
    tool,
    tool_ask,
    tool_bash,
    tool_list,
    tool_read,
    tool_replace,
    tool_search,
    tool_sloc,
    tool_todo,
    tool_webfetch,
)

from .cli import (
    _SESSIONS_DIR as _SESSIONS_DIR,
    _chat_command as _chat_command,
    _create_prompt_session as _create_prompt_session,
    _current_model_text as _current_model_text,
    _git_diff_shortstat as _git_diff_shortstat,
    _handle_ask as _handle_ask,
    _handle_audit as _handle_audit,
    _handle_debug_toggle as _handle_debug_toggle,
    _handle_load as _handle_load,
    _handle_model_switch as _handle_model_switch,
    _handle_save as _handle_save,
    _pick_model as _pick_model,
    _print_session_intro as _print_session_intro,
    _read_input as _read_input,
    _resolve_session as _resolve_session,
    _set_terminal_title as _set_terminal_title,
    _workspace as _workspace,
    audit as audit,
    chat as chat,    main as main,
    model as model,
    read_system_prompt as read_system_prompt,
    render_model_list as render_model_list,
    resolve_model_choice as resolve_model_choice,
    run as run,
)


if __name__ == "__main__":
    raise SystemExit(main())
