//! OpenCode setup and launcher commands.

use anyhow::{Context, Result, bail};
use serde_json::{Map, Value, json};
use std::fs;
use std::io::{IsTerminal as _, Read as _};
use std::path::Path;
use std::path::PathBuf;
use std::process::{Command, Stdio};

use crate::{audit, config, ui};

const GENERATED_MARKER: &str = "Generated by oy setup";

pub(crate) fn setup_command() -> Result<i32> {
    setup_workspace(true)
}

fn setup_workspace(report: bool) -> Result<i32> {
    let root = config::oy_root()?;
    let dir = root.join(".opencode");
    fs::create_dir_all(dir.join("agents"))
        .with_context(|| format!("failed to create {}", dir.join("agents").display()))?;
    fs::create_dir_all(dir.join("skills/oy-audit"))
        .with_context(|| format!("failed to create {}", dir.join("skills").display()))?;
    fs::create_dir_all(dir.join("skills/oy-review"))
        .with_context(|| format!("failed to create {}", dir.join("skills").display()))?;

    write_agent(&dir.join("agents/oy-auditor.md"), OY_AUDITOR_AGENT)?;
    write_agent(&dir.join("agents/oy-reviewer.md"), OY_REVIEWER_AGENT)?;
    write_agent(&dir.join("agents/oy-enhancer.md"), OY_ENHANCER_AGENT)?;
    write_agent(&dir.join("skills/oy-audit/SKILL.md"), OY_AUDIT_SKILL)?;
    write_agent(&dir.join("skills/oy-review/SKILL.md"), OY_REVIEW_SKILL)?;
    update_config(&dir.join("opencode.json"))?;

    if report {
        ui::success(format_args!(
            "installed OpenCode oy integration in {}",
            dir.display()
        ));
        ui::line("Restart OpenCode for the new MCP server, agents, skills, and commands to load.");
    }
    Ok(0)
}

pub(crate) fn launch_command(args: Vec<String>) -> Result<i32> {
    setup_workspace(false)?;
    run_opencode(args)
}

pub(crate) fn legacy_run_command(
    task: Vec<String>,
    continue_session: bool,
    resume: String,
    mode: config::SafetyMode,
    out: Option<PathBuf>,
) -> Result<i32> {
    setup_workspace(false)?;
    let prompt = collect_prompt(task)?;
    if prompt.trim().is_empty() {
        return legacy_chat_command(continue_session, resume, mode);
    }
    let mut args = vec!["run".to_string()];
    push_session_args(&mut args, continue_session, &resume);
    push_mode_args(&mut args, mode);
    if ui::is_json() {
        args.extend(["--format".to_string(), "json".to_string()]);
    }
    args.push(prompt);
    let code = run_opencode_capture(args, out.as_deref())?;
    Ok(code)
}

pub(crate) fn legacy_chat_command(
    continue_session: bool,
    resume: String,
    mode: config::SafetyMode,
) -> Result<i32> {
    setup_workspace(false)?;
    let mut args = Vec::new();
    push_session_args(&mut args, continue_session, &resume);
    push_mode_args(&mut args, mode);
    run_opencode(args)
}

pub(crate) fn legacy_model_command(model: Option<String>) -> Result<i32> {
    setup_workspace(false)?;
    let mut args = vec!["models".to_string()];
    if let Some(model) = model {
        args.push(model);
    }
    run_opencode(args)
}

pub(crate) fn legacy_audit_command(
    focus: Vec<String>,
    out: PathBuf,
    max_chunks: usize,
    format: audit::AuditOutputFormat,
) -> Result<i32> {
    setup_workspace(false)?;
    let mut message = String::from("Run an oy audit for this workspace.");
    if !focus.is_empty() {
        message.push_str(" Focus: ");
        message.push_str(&focus.join(" "));
        message.push('.');
    }
    message.push_str(&format!(
        " Write output to {}. Use max_chunks {}. Format: {}.",
        out.display(),
        max_chunks,
        format.name()
    ));
    run_opencode(vec![
        "run".to_string(),
        "--command".to_string(),
        "oy-audit".to_string(),
        message,
    ])
}

pub(crate) fn legacy_review_command(
    target: Option<String>,
    focus: Vec<String>,
    out: PathBuf,
    max_chunks: usize,
) -> Result<i32> {
    setup_workspace(false)?;
    let mut message = String::from("Run an oy review.");
    if let Some(target) = target.filter(|target| !target.trim().is_empty()) {
        message.push_str(" Target: ");
        message.push_str(&target);
        message.push('.');
    }
    if !focus.is_empty() {
        message.push_str(" Focus: ");
        message.push_str(&focus.join(" "));
        message.push('.');
    }
    message.push_str(&format!(
        " Write output to {}. Use max_chunks {}.",
        out.display(),
        max_chunks
    ));
    run_opencode(vec![
        "run".to_string(),
        "--command".to_string(),
        "oy-review".to_string(),
        message,
    ])
}

pub(crate) fn legacy_enhance_command(
    review_target: Option<String>,
    focus: Vec<String>,
    audit_max_chunks: usize,
    review_max_chunks: usize,
    mode: config::SafetyMode,
) -> Result<i32> {
    setup_workspace(false)?;
    let mut message =
        String::from("Run oy enhance: fix one actionable finding from ISSUES.md or REVIEW.md.");
    if let Some(target) = review_target.filter(|target| !target.trim().is_empty()) {
        message.push_str(" Review target: ");
        message.push_str(&target);
        message.push('.');
    }
    if !focus.is_empty() {
        message.push_str(" Focus: ");
        message.push_str(&focus.join(" "));
        message.push('.');
    }
    message.push_str(&format!(
        " Audit max chunks: {audit_max_chunks}. Review max chunks: {review_max_chunks}."
    ));
    let mut args = vec![
        "run".to_string(),
        "--command".to_string(),
        "oy-enhance".to_string(),
    ];
    push_mode_args(&mut args, mode);
    args.push(message);
    run_opencode(args)
}

fn run_opencode(args: Vec<String>) -> Result<i32> {
    let status = Command::new("opencode")
        .args(args)
        .status()
        .context("failed to launch opencode; install it or run `oy setup` first")?;
    Ok(status.code().unwrap_or(1))
}

fn run_opencode_capture(args: Vec<String>, out: Option<&Path>) -> Result<i32> {
    let Some(out) = out else {
        return run_opencode(args);
    };
    let output = Command::new("opencode")
        .args(args)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .context("failed to launch opencode; install it or run `oy setup` first")?;
    if !output.stderr.is_empty() {
        ui::err(&String::from_utf8_lossy(&output.stderr));
    }
    let code = output.status.code().unwrap_or(1);
    if code != 0 {
        return Ok(code);
    }
    let root = config::oy_root()?;
    let path = config::resolve_workspace_output_path(&root, out)?;
    config::write_workspace_file(&path, &output.stdout)?;
    ui::success(format_args!("wrote {}", path.display()));
    Ok(0)
}

fn collect_prompt(parts: Vec<String>) -> Result<String> {
    if !parts.is_empty() {
        return Ok(parts.join(" "));
    }
    if std::io::stdin().is_terminal() {
        return Ok(String::new());
    }
    let mut input = String::new();
    std::io::stdin().read_to_string(&mut input)?;
    Ok(input.trim().to_string())
}

fn push_session_args(args: &mut Vec<String>, continue_session: bool, resume: &str) {
    if continue_session {
        args.push("--continue".to_string());
    }
    if !resume.trim().is_empty() {
        args.extend(["--session".to_string(), resume.to_string()]);
    }
}

fn push_mode_args(args: &mut Vec<String>, mode: config::SafetyMode) {
    if mode == config::SafetyMode::Plan {
        args.extend(["--agent".to_string(), "plan".to_string()]);
    }
}

fn update_config(path: &Path) -> Result<()> {
    let mut root = if path.exists() {
        let text = fs::read_to_string(path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        serde_json::from_str::<Value>(&text)
            .with_context(|| format!("{} must be JSON for oy setup to update it", path.display()))?
    } else {
        json!({ "$schema": "https://opencode.ai/config.json" })
    };
    let object = root
        .as_object_mut()
        .ok_or_else(|| anyhow::anyhow!("{} must contain a JSON object", path.display()))?;
    object
        .entry("$schema")
        .or_insert_with(|| json!("https://opencode.ai/config.json"));
    merge_mcp(object);
    merge_commands(object);
    write_file(path, &format_json(&root)?)
}

fn merge_mcp(object: &mut Map<String, Value>) {
    let mcp = object
        .entry("mcp")
        .or_insert_with(|| Value::Object(Map::new()));
    if !mcp.is_object() {
        *mcp = Value::Object(Map::new());
    }
    mcp.as_object_mut().unwrap().insert(
        "oy".to_string(),
        json!({
            "type": "local",
            "command": ["oy", "mcp"],
            "enabled": true,
            "timeout": 300000
        }),
    );
}

fn merge_commands(object: &mut Map<String, Value>) {
    let command = object
        .entry("command")
        .or_insert_with(|| Value::Object(Map::new()));
    if !command.is_object() {
        *command = Value::Object(Map::new());
    }
    let command = command.as_object_mut().unwrap();
    command.insert(
        "oy-audit".to_string(),
        json!({
            "description": "Run an oy-style security audit using deterministic repo inputs.",
            "agent": "oy-auditor",
            "template": "Audit this workspace. Build deterministic input with the oy MCP tools, produce concrete findings with evidence, then call oy_render_audit_report."
        }),
    );
    command.insert(
        "oy-review".to_string(),
        json!({
            "description": "Run an oy-style code-quality review.",
            "agent": "oy-reviewer",
            "template": "Review this workspace or current diff. Use oy_git_diff_input when a target is provided or oy_repo_chunks for whole-workspace review, then call oy_render_review_report."
        }),
    );
    command.insert(
        "oy-enhance".to_string(),
        json!({
            "description": "Fix findings from ISSUES.md or REVIEW.md one at a time.",
            "agent": "oy-enhancer",
            "template": "Read ISSUES.md and REVIEW.md, select one high-confidence finding, fix it with OpenCode native tools, run targeted verification, and summarize the result."
        }),
    );
}

fn write_agent(path: &Path, body: &str) -> Result<()> {
    write_file(path, body)
}

fn write_file(path: &Path, body: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    if path.exists() {
        let current = fs::read_to_string(path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        if !current.contains(GENERATED_MARKER) && current != body {
            bail!(
                "refusing to overwrite non-oy file {}; move it aside or edit it manually",
                path.display()
            );
        }
    }
    fs::write(path, body).with_context(|| format!("failed to write {}", path.display()))
}

fn format_json(value: &Value) -> Result<String> {
    let mut text = serde_json::to_string_pretty(value)?;
    text.push('\n');
    Ok(text)
}

const OY_AUDITOR_AGENT: &str = r#"---
description: Runs oy-style security audits using deterministic MCP repo chunks and writes ISSUES.md/SARIF.
mode: subagent
permission:
  edit: deny
  bash: ask
---

<!-- Generated by oy setup -->

You are the oy security auditor. Use OpenCode's model/tool loop, but use oy MCP tools for deterministic repository inputs.

Workflow:
1. Call oy_repo_manifest to understand scope and security-relevant files.
2. Call oy_repo_chunks without a chunk number to get chunk summaries.
3. Review each relevant chunk by calling oy_repo_chunks with its 1-based chunk number.
4. Produce only concrete, evidence-backed findings with severity, title, locations, evidence, and remediation.
5. Call oy_render_audit_report to write ISSUES.md, or SARIF if requested.

Avoid speculative issues. Prefer fewer high-confidence findings over broad commentary.
"#;

const OY_REVIEWER_AGENT: &str = r#"---
description: Runs oy-style strict code-quality reviews over a git diff or whole workspace and writes REVIEW.md.
mode: subagent
permission:
  edit: deny
  bash: ask
---

<!-- Generated by oy setup -->

You are the oy code-quality reviewer. Focus on maintainability, correctness, decomposition, error handling, and tests.

Workflow:
1. If the user names a branch/commit/ref, call oy_git_diff_input for that target.
2. Otherwise call oy_repo_manifest and oy_repo_chunks for the workspace.
3. Review deterministic chunks with concrete file/line evidence.
4. Produce findings ordered by severity. Avoid style-only nitpicks unless they hide real maintenance risk.
5. Call oy_render_review_report to write REVIEW.md.
"#;

const OY_ENHANCER_AGENT: &str = r#"---
description: Fixes oy audit/review findings one at a time using OpenCode native edit and bash tools.
mode: subagent
permission:
  edit: ask
  bash: ask
---

<!-- Generated by oy setup -->

You are the oy enhancer. Read ISSUES.md and REVIEW.md, choose one actionable finding, fix it minimally, and verify it.

Rules:
1. Fix one finding per pass.
2. Prefer minimal, targeted edits.
3. Use OpenCode native edit/bash tools so all changes remain visible to the user.
4. Run focused verification when available.
5. Summarize the finding addressed, files changed, and verification result.
"#;

const OY_AUDIT_SKILL: &str = r#"---
name: oy-audit
description: oy audit, security audit, ISSUES.md, SARIF. Use when the user asks for an oy-style repository security audit.
---

# oy Audit

<!-- Generated by oy setup -->

Use the oy-auditor agent. Use oy MCP tools for deterministic repo manifest/chunk inputs and report rendering. Write findings to ISSUES.md by default.
"#;

const OY_REVIEW_SKILL: &str = r#"---
name: oy-review
description: oy review, code quality review, REVIEW.md. Use when the user asks for an oy-style strict code-quality review.
---

# oy Review

<!-- Generated by oy setup -->

Use the oy-reviewer agent. Prefer oy_git_diff_input for branch/commit reviews and oy_repo_chunks for whole-workspace reviews. Write findings to REVIEW.md by default.
"#;
